# Generated by Django 4.0.4 on 2022-07-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('created', models.DateField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth')], max_length=6)),
                ('is_done', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='todo.tag')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
